# Generated by Django 2.2.4 on 2020-06-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
