# Generated by Django 2.2.4 on 2020-06-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200613_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='description',
        ),
    ]
